stages:
  data_ingestion:
    cmd: python src/data_ignestion.py
    deps:
    - src/data_ignestion.py
    # params:
    # - data_ignestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim
  feature_enginnering:
    cmd: python src/feature_enginnering.py
    deps:
    - data/interim
    - src/feature_enginnering.py
    # params:
    # - feature_enginnering.max_features
    outs:
    - data/processed
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    # params:
    # - model_building.n_estimators
    # - model_building.random_state
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json

# metrics:
# - dvclive/metrics.json
# plots:
# - dvclive/plots/metrics:
#     x: step
# params:
# - dvclive/params.yaml

    



  